const routes = {
  MAIN_STACK: 'MAIN_STACK',
  LOGIN_STACK: 'LOGIN_STACK',
  NOTES_STACK: 'NOTES_STACK',

  LOGIN_SCREEN: 'LOGIN_SCREEN',

  NOTES_LIST_SCREEN: 'NOTES_LIST_SCREEN',
  CREATE_NOTE_SCREEN: 'CREATE_NOTE_SCREEN',
  EDIT_NOTE_SCREEN: 'EDIT_NOTE_SCREEN',
};

export default routes;
